/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siuxoes;

/**
 *
 * @author Siuxoes
 */
public class Categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FuentePersonalizada cf3 = new FuentePersonalizada("ANIME.ttf");
        Anime = new javax.swing.JButton();
        FuentePersonalizada cf2 = new FuentePersonalizada("WOW.ttf");
        WoW = new javax.swing.JButton();
        FuentePersonalizada cf = new FuentePersonalizada("LOL.ttf");
        Lol1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccione una categoría");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(528, 524));
        setResizable(false);

        Anime.setFont(cf3.MyFont(1, 34f));
        Anime.setText("Anime");
        Anime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimeActionPerformed(evt);
            }
        });

        WoW.setFont(cf2.MyFont(1, 22f));
        WoW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/292635_661341867225566_1983435009_n.png"))); // NOI18N
        WoW.setText("World of Warcraft");
        WoW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WoWActionPerformed(evt);
            }
        });

        Lol1.setFont(cf.MyFont(1, 22f));
        Lol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icon.111954.png"))); // NOI18N
        Lol1.setText("League of Legends");
        Lol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lol1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Anime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lol1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(WoW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(Anime, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lol1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WoW, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lol1ActionPerformed
        new Test(1).setVisible(true);
        dispose();
    }//GEN-LAST:event_Lol1ActionPerformed

    private void AnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimeActionPerformed
        new Test(2).setVisible(true);
        dispose();
    }//GEN-LAST:event_AnimeActionPerformed

    private void WoWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WoWActionPerformed
        new Test(3).setVisible(true);
        dispose();
    }//GEN-LAST:event_WoWActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anime;
    private javax.swing.JButton Lol1;
    private javax.swing.JButton WoW;
    // End of variables declaration//GEN-END:variables
}
